  // Mock data for the RocketDrop e-commerce site

  export const categories = [
    {
      id: 1,
      name: 'Electronics',
      slug: 'electronics',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 2,
      name: "Men's Wear",
      slug: 'mens-wear',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 3,
      name: "Women's Wear",
      slug: 'womens-wear',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 4,
      name: 'Jewelry',
      slug: 'jewelry',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 5,
      name: 'Digital Wear',
      slug: 'digital-wear',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 6,
      name: 'Home & Kitchen',
      slug: 'home-kitchen',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 7,
      name: 'Beauty',
      slug: 'beauty',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 8,
      name: 'Sports',
      slug: 'sports',
      imageUrl: '/images/categories/placeholder.svg',
    },
    {
      id: 9,
      name: 'Toys',
      slug: 'toys',
      imageUrl: '/images/categories/placeholder.svg',
    },
  ];

  export const products = [
    {
      id: 1,
      name: 'Wireless Bluetooth Earbuds',
      slug: 'wireless-bluetooth-earbuds',
      description: 'High-quality wireless earbuds with noise cancellation and long battery life.',
      price: 79.99,
      discountPrice: 59.99,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'electronics',
      rating: 4.5,
      reviewCount: 128,
      stock: 50,
      featured: true,
      trending: true,
      specifications: [
        { name: 'Battery Life', value: 'Up to 24 hours' },
        { name: 'Bluetooth Version', value: '5.2' },
        { name: 'Water Resistance', value: 'IPX4' },
      ],
    },
    {
      id: 2,
      name: 'Smart Fitness Tracker',
      slug: 'smart-fitness-tracker',
      description: 'Track your fitness goals with this advanced smart fitness tracker.',
      price: 99.99,
      discountPrice: null,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'electronics',
      rating: 4.2,
      reviewCount: 95,
      stock: 30,
      featured: true,
      trending: false,
      specifications: [
        { name: 'Battery Life', value: 'Up to 7 days' },
        { name: 'Water Resistance', value: '5 ATM' },
        { name: 'Display', value: '1.3" AMOLED' },
      ],
    },
    {
      id: 3,
      name: 'Premium Leather Wallet',
      slug: 'premium-leather-wallet',
      description: 'Handcrafted genuine leather wallet with RFID protection.',
      price: 49.99,
      discountPrice: 39.99,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'fashion',
      rating: 4.8,
      reviewCount: 210,
      stock: 100,
      featured: false,
      trending: true,
      specifications: [
        { name: 'Material', value: 'Genuine Leather' },
        { name: 'Dimensions', value: '4.5" x 3.5"' },
        { name: 'Card Slots', value: '8' },
      ],
    },
    {
      id: 4,
      name: 'Stainless Steel Water Bottle',
      slug: 'stainless-steel-water-bottle',
      description: 'Double-walled insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours.',
      price: 34.99,
      discountPrice: 29.99,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'home-kitchen',
      rating: 4.6,
      reviewCount: 175,
      stock: 80,
      featured: true,
      trending: true,
      specifications: [
        { name: 'Capacity', value: '24 oz' },
        { name: 'Material', value: '18/8 Stainless Steel' },
        { name: 'Insulation', value: 'Double-wall vacuum' },
      ],
    },
    {
      id: 5,
      name: 'Organic Face Serum',
      slug: 'organic-face-serum',
      description: 'Revitalize your skin with this organic vitamin C serum.',
      price: 29.99,
      discountPrice: null,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'beauty',
      rating: 4.7,
      reviewCount: 142,
      stock: 60,
      featured: true,
      trending: false,
      specifications: [
        { name: 'Volume', value: '30ml' },
        { name: 'Ingredients', value: 'Organic, Vegan' },
        { name: 'Skin Type', value: 'All Skin Types' },
      ],
    },
    {
      id: 6,
      name: 'Yoga Mat',
      slug: 'yoga-mat',
      description: 'Non-slip, eco-friendly yoga mat for comfortable practice.',
      price: 39.99,
      discountPrice: 34.99,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'sports',
      rating: 4.4,
      reviewCount: 88,
      stock: 40,
      featured: false,
      trending: true,
      specifications: [
        { name: 'Material', value: 'TPE, Eco-friendly' },
        { name: 'Dimensions', value: '72" x 24" x 6mm' },
        { name: 'Weight', value: '2.5 lbs' },
      ],
    },
    {
      id: 7,
      name: 'Educational Building Blocks',
      slug: 'educational-building-blocks',
      description: 'Colorful building blocks for children to develop creativity and motor skills.',
      price: 24.99,
      discountPrice: 19.99,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'toys',
      rating: 4.9,
      reviewCount: 156,
      stock: 70,
      featured: true,
      trending: true,
      specifications: [
        { name: 'Age Range', value: '3+ years' },
        { name: 'Pieces', value: '100' },
        { name: 'Material', value: 'Non-toxic ABS Plastic' },
      ],
    },
    {
      id: 8,
      name: 'Portable Bluetooth Speaker',
      slug: 'portable-bluetooth-speaker',
      description: 'Waterproof portable speaker with 360° sound and 20-hour battery life.',
      price: 89.99,
      discountPrice: 69.99,
      imageUrl: '/images/products/placeholder.svg',
      images: [
        '/images/products/placeholder.svg',
        '/images/products/placeholder.svg',
      ],
      category: 'electronics',
      rating: 4.3,
      reviewCount: 112,
      stock: 45,
      featured: false,
      trending: true,
      specifications: [
        { name: 'Battery Life', value: 'Up to 20 hours' },
        { name: 'Water Resistance', value: 'IPX7' },
        { name: 'Connectivity', value: 'Bluetooth 5.0' },
      ],
    },
  ];