// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import { Footer } from "@/components/footer";
import { AuthProvider } from '@/app/contexts/AuthContext';
import ConditionalNavigation from '@/components/ConditionalNavigation';
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {/* Conditional navigation for users only */}
          <ConditionalNavigation />

          {/* Render the page content */}
          {children}

          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}






// import { Geist, Geist_Mono } from "next/font/google";
// import { Navigation } from "@/components/navbar";
// import { Footer } from "@/components/footer";
// import { AuthProvider } from '@/app/contexts/AuthContext';
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <AuthProvider>
//           <Navigation />
//           {children}
//           <Footer />
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
